### ISSUE TITLE
Setuptools fails importing module cli: No module named cli

### ISSUE THREAD

**Issue by shakaran** [jvrsantacruz/mp3hash#1]
I don't know if it is a problem with my paths or some weird thing that I am doing.

I just did a git clone of your project, then:

```
$ sudo python setup.py install
running install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing mp3hash.egg-info/PKG-INFO
writing top-level names to mp3hash.egg-info/top_level.txt
writing dependency_links to mp3hash.egg-info/dependency_links.txt
writing entry points to mp3hash.egg-info/entry_points.txt
reading manifest file 'mp3hash.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'mp3hash.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
running build_py
creating build/bdist.linux-i686/egg
creating build/bdist.linux-i686/egg/tests
copying build/lib.linux-i686-2.7/tests/__init__.py -> build/bdist.linux-i686/egg/tests
creating build/bdist.linux-i686/egg/tests/unit
copying build/lib.linux-i686-2.7/tests/unit/test_parse_7bitint.py -> build/bdist.linux-i686/egg/tests/unit
copying build/lib.linux-i686-2.7/tests/unit/test_id3v1.py -> build/bdist.linux-i686/egg/tests/unit
copying build/lib.linux-i686-2.7/tests/unit/__init__.py -> build/bdist.linux-i686/egg/tests/unit
copying build/lib.linux-i686-2.7/tests/unit/test_id3v1_extended.py -> build/bdist.linux-i686/egg/tests/unit
copying build/lib.linux-i686-2.7/tests/unit/test_id3v2.py -> build/bdist.linux-i686/egg/tests/unit
creating build/bdist.linux-i686/egg/tests/integration
copying build/lib.linux-i686-2.7/tests/integration/__init__.py -> build/bdist.linux-i686/egg/tests/integration
copying build/lib.linux-i686-2.7/tests/integration/test_cli.py -> build/bdist.linux-i686/egg/tests/integration
copying build/lib.linux-i686-2.7/tests/integration/test_hash.py -> build/bdist.linux-i686/egg/tests/integration
byte-compiling build/bdist.linux-i686/egg/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/tests/unit/test_parse_7bitint.py to test_parse_7bitint.pyc
byte-compiling build/bdist.linux-i686/egg/tests/unit/test_id3v1.py to test_id3v1.pyc
byte-compiling build/bdist.linux-i686/egg/tests/unit/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/tests/unit/test_id3v1_extended.py to test_id3v1_extended.pyc
byte-compiling build/bdist.linux-i686/egg/tests/unit/test_id3v2.py to test_id3v2.pyc
byte-compiling build/bdist.linux-i686/egg/tests/integration/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/tests/integration/test_cli.py to test_cli.pyc
byte-compiling build/bdist.linux-i686/egg/tests/integration/test_hash.py to test_hash.pyc
creating build/bdist.linux-i686/egg/EGG-INFO
copying mp3hash.egg-info/PKG-INFO -> build/bdist.linux-i686/egg/EGG-INFO
copying mp3hash.egg-info/SOURCES.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying mp3hash.egg-info/dependency_links.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying mp3hash.egg-info/entry_points.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying mp3hash.egg-info/top_level.txt -> build/bdist.linux-i686/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/mp3hash-0.0.6-py2.7.egg' and adding 'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing mp3hash-0.0.6-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/mp3hash-0.0.6-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/mp3hash-0.0.6-py2.7.egg
Extracting mp3hash-0.0.6-py2.7.egg to /usr/local/lib/python2.7/dist-packages
mp3hash 0.0.6 is already the active version in easy-install.pth
Installing mp3hash script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/mp3hash-0.0.6-py2.7.egg
Processing dependencies for mp3hash==0.0.6
Finished processing dependencies for mp3hash==0.0.6
```

Then I try to execute the binary (without arguments):

```
$ mp3hash
Traceback (most recent call last):
  File "/usr/local/bin/mp3hash", line 9, in <module>
    load_entry_point('mp3hash==0.0.6', 'console_scripts', 'mp3hash')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 343, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2307, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2013, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named cli
```

Binary path

```
$ which mp3hash
/usr/local/bin/mp3hash
```

Tree path:

```
$ tree /usr/local/lib/python2.7/dist-packages/mp3hash-0.0.6-py2.7.egg
/usr/local/lib/python2.7/dist-packages/mp3hash-0.0.6-py2.7.egg
├── EGG-INFO
│   ├── dependency_links.txt
│   ├── entry_points.txt
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── top_level.txt
│   └── zip-safe
└── tests
    ├── __init__.py
    ├── __init__.pyc
    ├── integration
    │   ├── __init__.py
    │   ├── __init__.pyc
    │   ├── test_cli.py
    │   ├── test_cli.pyc
    │   ├── test_hash.py
    │   └── test_hash.pyc
    └── unit
        ├── __init__.py
        ├── __init__.pyc
        ├── test_id3v1_extended.py
        ├── test_id3v1_extended.pyc
        ├── test_id3v1.py
        ├── test_id3v1.pyc
        ├── test_id3v2.py
        ├── test_id3v2.pyc
        ├── test_parse_7bitint.py
        └── test_parse_7bitint.pyc

4 directories, 24 files
```

It seems that I am not getting any mp3hash.py or cli.py file installed via setup.py.

**Comment by jvrsantacruz** [comment]
Thanks for this thorough and detailed error report! It allowed me to spot the problem at once.

You're totally right, the `cli.py` file is not being included by distribute along with the rest of the files. `setuptools.find_packages` seems to have no prob finding `mp3hash.py`, but `cli.py` it's sadly ignored.

I didn't notice this error as I'm always running my tests from the package root directory, where `cli.py` is available in path.

I think I just fixed this yesterday with this commit [https://github.com/jvrsantacruz/mp3hash/commit/bbf2a284ac25eb14f1dba301bd958bfe675e6457] which I just uploaded now, including some new tests.
It should be quite fixed after this last changes.

Thanks for reporting this error!
